name: click_tooltip
description: "A custom tooltip view"
version: 0.0.2
homepage: https://github.com/riad804/click_tooltip
repository: https://github.com/riad804/click_tooltip
issue_tracker: https://github.com/riad804/click_tooltip/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true