name: Flutter Package CI/CD

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Static analysis
      - name: Analyze
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Check formatting
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Setup pub credentials
        run: |
          mkdir -p ~/.pub-cache
          echo "${{ secrets.PUB_DEV_CREDENTIALS }}" > ~/.pub-cache/credentials.json

      - name: Publish to pub.dev
        run: dart pub publish --force
